### ISSUE TITLE
[fuzz] add with overflow (2)

### ISSUE THREAD

**Issue by nagisa** [PistonDevelopers/inflate#17]
Code:

```
extern crate inflate;

fn main() {
    let data = b"\xdd\xff\xff*M\x94ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\x01\x09\x00\x00\xf2\xf2MM\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00*M\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00MMMM\xff\xffM\xff\x00;MM0*\x00\x00\x00\x00\x00\x00\x0a";
    inflate::InflateStream::new().update(data);

}
```

Result:

```
thread 'main' panicked at 'attempt to add with overflow', lib.rs:269
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: inflate::CodeLengthReader::new
             at ./lib.rs:302
   1: inflate::InflateStream::next_state
             at ./lib.rs:907
   2: inflate::InflateStream::update
             at ./lib.rs:1039
   3: test::main
             at /home/nagisa/Documents/rust/inflate/examples/test.rs:5
```

Backtrace is different from #16

**Comment by eddyb** [comment]
Frankly, every addition, subtraction or multiplication may fail, it's probably easier to replace all of them with `Wrapping` or something, if there's too many of them.
