### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/inflate#41]
https://github.com/PistonDevelopers/image-png/pull/77 is failing with the error:

```
"tests/pngsuite/oi9n0g16.png": thread 'render_images' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/sven/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.4.1/src/lib.rs:753:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Backtrace:

```
"tests/pngsuite/oi9n0g16.png": thread 'render_images' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/sven/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.4.1/src/lib.rs:753:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:216
   4: std::panicking::begin_panic
             at libstd/panicking.rs:400
   5: std::panicking::try::do_call
             at libstd/panicking.rs:347
   6: std::panicking::try::do_call
             at libstd/panicking.rs:323
   7: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at libcore/panicking.rs:71
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at libcore/panicking.rs:58
   9: inflate::InflateStream::next_state
             at /Users/sven/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.4.1/src/lib.rs:753
  10: inflate::InflateStream::next_state::{{closure}}
             at /Users/sven/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.4.1/src/lib.rs:1033
  11: png::decoder::stream::StreamingDecoder::next_state
             at src/decoder/stream.rs:361
  12: std::panicking::begin_panic
             at src/decoder/stream.rs:168
  13: <png::decoder::ReadDecoder<R>>::decode_next
             at ./src/decoder/mod.rs:109
  14: <png::decoder::Reader<R>>::next_raw_interlaced_row
             at ./src/decoder/mod.rs:428
  15: <png::decoder::Reader<R>>::next_interlaced_row
             at ./src/decoder/mod.rs:254
  16: <png::decoder::Reader<R>>::next_row
             at ./src/decoder/mod.rs:238
  17: <png::decoder::Reader<R>>::next_frame
             at ./src/decoder/mod.rs:229
  18: check_testimages::render_images::{{closure}}
             at tests/check_testimages.rs:67
  19: check_testimages::process_images
             at tests/check_testimages.rs:26
  20: check_testimages::render_images
             at tests/check_testimages.rs:63
  21: check_testimages::__test::TESTS::{{closure}}
             at tests/check_testimages.rs:62
  22: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  23: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1471
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:783
  24: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102


failures:
    render_images
```

**Comment by bvssvni** [comment]
I tried putting this right before the line:

```rust
                if data.len() == 0 {
                    return ok_bytes!(0, Finished);
                }
```

This resulted in the following error:

```
"tests/pngsuite-extra/basi3p01_2.png": 2570215674
"tests/pngsuite-extra/basi3p02_2.png": 419215269
"tests/bugfixes/acid2.png": 2380843583
"tests/bugfixes/invalid_palette_index.png": 3040120786
"tests/bugfixes/issue#403.png": 2961280239
"tests/bugfixes/x_ihdr_missing.png": Expected failure
"tests/bugfixes/x_unexpected_eof.png": Expected failure
thread 'render_images' panicked at 'assertion failed: `(left == right)`
  left: `"101827364"`,
 right: `"4021661486"`', tests/check_testimages.rs:54:9
```

I was just guessing from looking at the code.

**Comment by bvssvni** [comment]
Seems that this bug was introduced in https://github.com/PistonDevelopers/inflate/pull/39.

**Comment by bvssvni** [comment]
I think I've solved it.
